2017-10-17 09:33:49,960 > INFO > Starting MonitoringEngine
2017-10-17 09:33:50,914 > INFO > Starting MonitoringEngine
2017-10-17 09:42:52,221 > INFO > Starting MonitoringEngine
2017-10-17 09:42:53,154 > INFO > Starting MonitoringEngine
2017-10-19 07:59:06,615 > INFO > Starting MonitoringEngine
2017-10-19 07:59:08,042 > INFO > Starting MonitoringEngine
2017-10-19 08:19:48,439 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:20:42,646 > INFO > Starting MonitoringEngine
2017-10-19 08:20:53,176 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:23:14,579 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:25:20,417 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:31:44,599 > INFO > Starting MonitoringEngine
2017-10-19 08:31:54,324 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:33:54,366 > INFO > Starting MonitoringEngine
2017-10-19 08:35:44,807 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 11:45:21,817 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:47:08,257 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:48:18,261 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:49:32,307 > INFO > Starting MonitoringEngine
2017-10-19 11:50:18,562 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:42,290 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:54,001 > INFO > Starting MonitoringEngine
2017-10-19 11:57:42,327 > INFO > Starting MonitoringEngine
2017-10-19 11:57:55,245 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:59:06,990 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:00:18,776 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n- ci'
2017-10-19 12:00:21,949 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:02:53,525 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:08:26,951 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:09:41,718 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:10:31,682 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:11:55,831 > INFO > Starting MonitoringEngine
2017-10-21 11:10:00,965 > INFO > Starting MonitoringEngine
2017-10-21 11:10:02,714 > INFO > Starting MonitoringEngine
2017-10-21 11:54:29,848 > INFO > Starting MonitoringEngine
2017-10-21 11:54:34,969 > INFO > Starting MonitoringEngine
2017-10-21 11:54:43,240 > INFO > Starting MonitoringEngine
2017-10-21 11:56:49,422 > INFO > Starting MonitoringEngine
2017-10-21 12:06:08,141 > INFO > Starting MonitoringEngine
2017-10-21 12:06:37,631 > INFO > Starting MonitoringEngine
2017-10-21 18:40:32,384 > INFO > Starting MonitoringEngine
2017-10-21 18:40:34,859 > INFO > Starting MonitoringEngine
2017-10-21 18:44:22,941 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:46:46,369 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:48:54,762 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:52:59,079 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
