2017-10-17 09:33:49,960 > INFO > Starting MonitoringEngine
2017-10-17 09:33:50,914 > INFO > Starting MonitoringEngine
2017-10-17 09:42:52,221 > INFO > Starting MonitoringEngine
2017-10-17 09:42:53,154 > INFO > Starting MonitoringEngine
2017-10-19 07:59:06,615 > INFO > Starting MonitoringEngine
2017-10-19 07:59:08,042 > INFO > Starting MonitoringEngine
2017-10-19 08:19:48,439 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:20:42,646 > INFO > Starting MonitoringEngine
2017-10-19 08:20:53,176 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:23:14,579 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:25:20,417 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:31:44,599 > INFO > Starting MonitoringEngine
2017-10-19 08:31:54,324 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 08:33:54,366 > INFO > Starting MonitoringEngine
2017-10-19 08:35:44,807 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\nnetw'
2017-10-19 11:45:21,817 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:47:08,257 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:48:18,261 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:49:32,307 > INFO > Starting MonitoringEngine
2017-10-19 11:50:18,562 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:42,290 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:53:54,001 > INFO > Starting MonitoringEngine
2017-10-19 11:57:42,327 > INFO > Starting MonitoringEngine
2017-10-19 11:57:55,245 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 11:59:06,990 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:00:18,776 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\n- ci'
2017-10-19 12:00:21,949 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:02:53,525 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:08:26,951 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:09:41,718 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:10:31,682 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-19 12:11:55,831 > INFO > Starting MonitoringEngine
2017-10-21 11:10:00,965 > INFO > Starting MonitoringEngine
2017-10-21 11:10:02,714 > INFO > Starting MonitoringEngine
2017-10-21 11:54:29,848 > INFO > Starting MonitoringEngine
2017-10-21 11:54:34,969 > INFO > Starting MonitoringEngine
2017-10-21 11:54:43,240 > INFO > Starting MonitoringEngine
2017-10-21 11:56:49,422 > INFO > Starting MonitoringEngine
2017-10-21 12:06:08,141 > INFO > Starting MonitoringEngine
2017-10-21 12:06:37,631 > INFO > Starting MonitoringEngine
2017-10-21 18:40:32,384 > INFO > Starting MonitoringEngine
2017-10-21 18:40:34,859 > INFO > Starting MonitoringEngine
2017-10-21 18:44:22,941 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:46:46,369 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:48:54,762 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 18:52:59,079 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 441, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1230, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1224, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-21 08:49:35,932 > INFO > Starting MonitoringEngine
2017-10-21 08:49:36,628 > INFO > Starting MonitoringEngine
2017-10-21 08:50:19,892 > INFO > Starting MonitoringEngine
2017-10-21 08:50:20,296 > INFO > Starting MonitoringEngine
2017-10-21 10:54:28,388 > INFO > Starting MonitoringEngine
2017-10-21 10:54:29,021 > INFO > Starting MonitoringEngine
2017-10-22 02:47:50,940 > INFO > Starting MonitoringEngine
2017-10-22 02:47:52,066 > INFO > Starting MonitoringEngine
2017-10-22 02:52:50,540 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 03:05:49,526 > INFO > Starting MonitoringEngine
2017-10-22 03:05:50,011 > INFO > Starting MonitoringEngine
2017-10-22 03:08:30,032 > INFO > Starting MonitoringEngine
2017-10-22 03:08:30,478 > INFO > Starting MonitoringEngine
2017-10-22 05:22:31,779 > INFO > Starting MonitoringEngine
2017-10-22 05:37:47,330 > INFO > Starting MonitoringEngine
2017-10-22 06:36:32,336 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:24:59,806 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:31:37,402 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-22 07:33:42,354 > INFO > Starting MonitoringEngine
2017-10-22 07:34:00,966 > INFO > Starting MonitoringEngine
2017-10-22 07:34:04,606 > INFO > Starting MonitoringEngine
2017-10-22 07:34:32,660 > INFO > Starting MonitoringEngine
2017-10-22 07:35:13,693 > ERROR > get_xl_group
Traceback (most recent call last):
  File "websnap.py", line 399, in get_xl_group
    xl = pandas.ExcelFile(xl_file)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 260, in __init__
    self.book = xlrd.open_workbook(io)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 91, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1271, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1265, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
XLRDError: Unsupported format, or corrupt file: Expected BOF record; found '---\ncred'
2017-10-25 06:13:40,758 > INFO > Starting MonitoringEngine
2017-10-25 06:13:41,517 > INFO > Starting MonitoringEngine
2017-10-25 06:14:11,628 > INFO > Starting MonitoringEngine
2017-10-25 06:14:12,097 > INFO > Starting MonitoringEngine
2017-10-25 10:53:07,741 > INFO > Starting MonitoringEngine
2017-10-25 10:53:08,941 > INFO > Starting MonitoringEngine
2017-10-25 10:53:45,006 > INFO > Starting MonitoringEngine
2017-10-25 10:55:07,176 > INFO > Starting MonitoringEngine
2017-10-25 10:55:39,817 > INFO > Starting MonitoringEngine
2017-10-25 10:57:56,691 > INFO > Starting MonitoringEngine
2017-10-25 10:58:09,745 > INFO > Starting MonitoringEngine
2017-10-25 10:58:27,844 > INFO > Starting MonitoringEngine
2017-10-25 12:26:04,775 > INFO > Starting MonitoringEngine
2017-10-25 12:26:06,351 > INFO > Starting MonitoringEngine
2017-10-25 12:33:15,217 > INFO > Starting MonitoringEngine
2017-10-25 12:33:15,625 > INFO > Starting MonitoringEngine
2017-10-25 12:35:12,771 > INFO > Starting MonitoringEngine
2017-10-25 12:42:43,396 > INFO > Starting MonitoringEngine
2017-10-25 12:43:49,530 > INFO > Starting MonitoringEngine
2017-10-25 12:45:13,680 > INFO > Starting MonitoringEngine
2017-10-25 12:45:36,676 > INFO > Starting MonitoringEngine
2017-10-25 12:45:54,659 > INFO > Starting MonitoringEngine
2017-10-25 12:46:00,907 > INFO > Starting MonitoringEngine
2017-10-25 12:51:24,784 > INFO > Starting MonitoringEngine
2017-10-25 12:51:25,206 > INFO > Starting MonitoringEngine
2017-10-25 12:52:14,326 > INFO > Starting MonitoringEngine
2017-10-25 12:59:04,462 > INFO > Starting MonitoringEngine
2017-10-25 12:59:04,873 > INFO > Starting MonitoringEngine
2017-10-25 13:09:06,107 > INFO > Starting MonitoringEngine
2017-10-25 13:15:00,393 > INFO > Starting MonitoringEngine
2017-10-25 13:16:50,606 > INFO > Starting MonitoringEngine
2017-10-25 13:18:46,347 > INFO > Starting MonitoringEngine
2017-10-25 13:19:12,434 > INFO > Starting MonitoringEngine
2017-10-25 13:19:26,979 > INFO > Starting MonitoringEngine
2017-10-25 13:20:04,045 > INFO > Starting MonitoringEngine
2017-10-25 13:20:28,081 > INFO > Starting MonitoringEngine
2017-10-25 13:20:54,122 > INFO > Starting MonitoringEngine
2017-10-25 13:21:54,361 > INFO > Starting MonitoringEngine
2017-10-25 13:22:36,068 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-25 13:23:09,752 > INFO > Starting MonitoringEngine
2017-10-26 19:37:58,892 > INFO > Starting MonitoringEngine
2017-10-26 19:37:59,727 > INFO > Starting MonitoringEngine
2017-10-26 20:04:02,195 > INFO > merge_js_yaml > Some data missed in JS , skipping
2017-10-26 20:07:05,296 > INFO > merge_js_yaml > Some data missed in JS , skipping
